### ISSUE TITLE
yaml library pukes on []

### ISSUE THREAD

**Issue by newhook** [esilkensen/yaml#21]
The following yaml causes an error.

```
check: []
```

I get when loading this yaml:

```
make-constructor: broke its own contract
  promised: (or/c yaml? void?)
  produced: '#hash(("checks" . ()))
  in: the range of
      the range of
      (->*
       ()
       (input-port?)
       (values
        (-> boolean?)
        (-> (or/c yaml? void?))
        (-> (or/c yaml? #f))))
  contract from: 
      <pkgs>/yaml/yaml/constructor.rkt
  blaming: <pkgs>/yaml/yaml/constructor.rkt
   (assuming the contract is correct)
  at: <pkgs>/yaml/yaml/constructor.rkt:21.3
```

**Comment by samth** [comment]
Here's a fix: replace `construct-yaml-seq` with:

```racket
(define (construct-yaml-seq node)
    (define v (construct-sequence node))
    (if (null? v)
        (yaml-null)
        v))
```

**Comment by esilkensen** [comment]
Thanks Matthew and Sam!

I think the `yaml?` should be changed also to accept empty lists (and sets)?  I must have thought otherwise at some point, but can't think of any reason those shouldn't be valid YAML.

**Comment by samth** [comment]
I looked at the docs and it explicitly says that empty lists aren't valid unless they're `yaml-null`. So if you change that, you might want to change the docs too.
