### ISSUE TITLE
Support writing hash tables in an ordered manner (possibly with an optional keyword argument)

### ISSUE THREAD

**Issue by EFanZh** [esilkensen/yaml#33]
I think for an object that has many attributes, the output will be easier for humans to read if the keys are ordered. This may also apply to sets.

**Comment by esilkensen** [comment]
I agree it would be nice to be able to control this. I'll think about what keyword options might make sense. Also, something I'd like to do is provide a public API for writing custom representers, a way to define YAML representations of arbitrary Racket types. That could include overriding existing behavior; for example, saying: "here is a new representer for `hash?`: iterate over the keys in this order"

**Comment by esilkensen** [comment]
I've just pushed a first pass at this that adds two keyword arguments to the YAML output procedures: `#:sort-mapping` defining a comparison function, and `#:sort-mapping-key` for extracting a value to sort on. The values passed to the comparison function are key-value pairs.

So to write a hash table with its keys sorted, can do: `(write-yaml table #:sort-mapping string<? #:sort-mapping-key car)`

**Comment by EFanZh** [comment]
I’ve tried the latest version, and it works, thanks.
